[build]
  command = "npm run build"
  publish = "_site"

[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200

  [[redirects]]
  from = "/admin"
  to = "/admin/"
  status = 301
  
  [[redirects]]
  from = "/confirmation"
  to = "/confirmation.html"
  status = 200

