backend:
  name: git-gateway
  branch: main   # branche GitHub où se trouvent tes fichiers contenus (change si besoin)

media_folder: "static/uploads"  # dossier pour stocker les médias uploadés
public_folder: "/uploads"       # chemin public des médias

site_url: "https://ton-site.netlify.app"  # remplace par ton URL Netlify

collections:
  - name: "pages"
    label: "Pages"
    folder: "datacontent"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Titre", name: "title", widget: "string" }
      - { label: "Contenu", name: "body", widget: "markdown" }
